# Generated by Django 5.0.3 on 2024-04-30 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bank_brokerage_company_cryptowallet_government_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_type',
        ),
    ]
